class PdfService {
  /**
   * Generates a valid PDF binary buffer from a report dataset.
   * Uses standard PDF specs (version 1.4) to construct a text-based document.
   * @param {string} title - Report title
   * @param {Array<Object>} data - Report data records
   * @param {Array<Object>} columns - Column definitions { key, title }
   * @param {string} [operatorName='System'] - User generating the report
   * @returns {Buffer} PDF binary buffer
   */
  generateBuffer(title, data, columns, operatorName = 'System') {
    const lines = [];

    // 1. PDF Header
    lines.push('%PDF-1.4');

    // Store objects and cross-reference byte offsets
    const objects = [];
    const offsets = [];

    const addObject = (content) => {
      const objId = objects.length + 1;
      objects.push({ id: objId, content });
      return objId;
    };

    // 2. Build Content Streams (Pages)
    // We group records to fit ~40 rows per page
    const pageSize = 40;
    const pagesCount = Math.max(1, Math.ceil(data.length / pageSize));
    const pageObjectsIds = [];

    // Font object (Helvetica standard)
    const fontObjId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>');
    const fontBoldObjId = addObject('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>');

    for (let pIdx = 0; pIdx < pagesCount; pIdx++) {
      const pageData = data.slice(pIdx * pageSize, (pIdx + 1) * pageSize);
      
      // Page stream text commands
      const streamLines = [];
      streamLines.push('BT');
      
      // Document Title
      streamLines.push(`/F2 18 Tf`); // Use Bold font 18pt
      streamLines.push(`50 770 Td`);
      streamLines.push(`(${title.replace(/[()]/g, '')}) Tj`);
      
      // Metadata (Date / Generated by)
      streamLines.push(`/F1 9 Tf`); // Use Standard font 9pt
      streamLines.push(`0 -25 Td`);
      streamLines.push(`(Generated on: ${new Date().toLocaleDateString()} | By: ${operatorName} | Page: ${pIdx + 1} of ${pagesCount}) Tj`);
      
      // Header row columns
      streamLines.push(`/F2 10 Tf`);
      streamLines.push(`0 -35 Td`);
      
      let xOffset = 0;
      columns.forEach((col, cIdx) => {
        const textVal = `${col.title}`.substring(0, 20);
        if (cIdx === 0) {
          streamLines.push(`(${textVal}) Tj`);
        } else {
          // Move cursor to next column coordinate
          streamLines.push(`${110} 0 Td`);
          streamLines.push(`(${textVal}) Tj`);
          xOffset += 110;
        }
      });

      // Revert column movements
      if (xOffset > 0) {
        streamLines.push(`-${xOffset} -20 Td`);
      } else {
        streamLines.push(`0 -20 Td`);
      }

      // Render Rows
      streamLines.push(`/F1 8 Tf`);
      pageData.forEach(record => {
        let rxOffset = 0;
        columns.forEach((col, cIdx) => {
          let val = record[col.key];
          if (val === undefined || val === null) val = '';
          if (val instanceof Date) val = val.toLocaleDateString();
          
          const textVal = String(val).substring(0, 20).replace(/[()]/g, '');

          if (cIdx === 0) {
            streamLines.push(`(${textVal}) Tj`);
          } else {
            streamLines.push(`${110} 0 Td`);
            streamLines.push(`(${textVal}) Tj`);
            rxOffset += 110;
          }
        });
        
        // Revert X movement and jump down
        if (rxOffset > 0) {
          streamLines.push(`-${rxOffset} -14 Td`);
        } else {
          streamLines.push(`0 -14 Td`);
        }
      });

      streamLines.push('ET');
      const streamContent = streamLines.join('\n');
      
      const streamObjId = addObject(
        `<< /Length ${streamContent.length} >>\nstream\n${streamContent}\nendstream`
      );
      
      const pageObjId = addObject(
        `<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 ${fontObjId} 0 R /F2 ${fontBoldObjId} 0 R >> >> /Contents ${streamObjId} 0 R >>`
      );
      
      pageObjectsIds.push(pageObjId);
    }

    // Catalog & Page tree objects (we insert them into indices 1 and 2 by standard)
    const pageTreeKids = pageObjectsIds.map(id => `${id} 0 R`).join(' ');
    
    // We insert the page tree object at index objects.length + 1
    const pageTreeId = objects.length + 1;
    const catalogId = pageTreeId + 1;

    // Create Page tree and Catalog content
    const pageTreeContent = `<< /Type /Pages /Kids [ ${pageTreeKids} ] /Count ${pagesCount} /MediaBox [ 0 0 595 842 ] >>`;
    const catalogContent = `<< /Type /Catalog /Pages ${pageTreeId} 0 R >>`;

    objects.push({ id: pageTreeId, content: pageTreeContent });
    objects.push({ id: catalogId, content: catalogContent });

    // 3. Assemble PDF and compute offsets
    let pdfContent = '%PDF-1.4\n';
    
    // Sort objects by ID
    objects.sort((a, b) => a.id - b.id);

    objects.forEach(obj => {
      offsets[obj.id] = pdfContent.length;
      pdfContent += `${obj.id} 0 obj\n${obj.content}\nendobj\n`;
    });

    // 4. Cross-Reference Table
    const xrefOffset = pdfContent.length;
    pdfContent += 'xref\n';
    pdfContent += `0 ${objects.length + 1}\n`;
    pdfContent += '0000000000 65535 f \n';

    for (let idx = 1; idx <= objects.length; idx++) {
      const offsetStr = String(offsets[idx]).padStart(10, '0');
      pdfContent += `${offsetStr} 00000 n \n`;
    }

    // 5. Trailer
    pdfContent += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\n`;
    pdfContent += 'startxref\n';
    pdfContent += `${xrefOffset}\n`;
    pdfContent += '%%EOF';

    return Buffer.from(pdfContent, 'binary');
  }
}

export default new PdfService();
