/**
 * HomeoVault - Global Application Constants
 */

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
};

export const ROLES = {
  ADMINISTRATOR: 'Administrator',
  FAMILY_MEMBER: 'Family Member'
};

export const AUDIT_ACTIONS = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETE: 'PASSWORD_RESET_COMPLETE',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_STATUS_TOGGLE: 'USER_STATUS_TOGGLE',
  CACHE_FLUSH: 'CACHE_FLUSH',
  DATA_EXPORT: 'DATA_EXPORT',
  DATA_IMPORT: 'DATA_IMPORT'
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100
};

export const SECURITY = {
  SALT_ROUNDS: 10,
  ACCOUNT_LOCKOUT_ATTEMPTS: 5,
  ACCOUNT_LOCKOUT_DURATION_MS: 15 * 60 * 1000, // 15 mins
  PASSWORD_RESET_EXPIRY_MS: 1 * 60 * 60 * 1000, // 1 hour
  SESSION_EXPIRY_MS: 24 * 60 * 60 * 1000 // 24 hours
};

export default {
  HTTP_STATUS,
  ROLES,
  AUDIT_ACTIONS,
  PAGINATION,
  SECURITY
};
